const now = Date.now();
const day = 86400000;

export const DEMO_COMPANY = {
  id: "demo-company",
  name: "Demo Company",
  slug: "demo",
  logoUrl: "/dbfb-logo-white.svg",
  primaryColor: "#EC5F5B",
  secondaryColor: "#d44f4c",
  accentColor: "#FFF0EF",
  textOnPrimary: "#FFFFFF",
  address: "123 Business Park, London, EC1A 1BB",
  website: "https://dbfb.co.uk",
  createdAt: new Date(now - day * 90),
  updatedAt: new Date(),
};

export const DEMO_MANAGER = {
  id: "demo-manager",
  name: "Sarah Manager",
  email: "manager@demo.com",
  role: "MANAGER",
  department: "Finance",
  jobTitle: "Finance Manager",
  isActive: true,
  createdAt: new Date(now - day * 90),
};

export const DEMO_EMPLOYEES = [
  DEMO_MANAGER,
  {
    id: "demo-user",
    name: "John Smith",
    email: "john@demo.com",
    role: "EMPLOYEE",
    department: "Sales",
    jobTitle: "Sales Executive",
    isActive: true,
    createdAt: new Date(now - day * 60),
  },
  {
    id: "demo-user-2",
    name: "Emma Wilson",
    email: "emma@demo.com",
    role: "EMPLOYEE",
    department: "Marketing",
    jobTitle: "Marketing Lead",
    isActive: true,
    createdAt: new Date(now - day * 45),
  },
  {
    id: "demo-user-3",
    name: "James Taylor",
    email: "james@demo.com",
    role: "EMPLOYEE",
    department: "Engineering",
    jobTitle: "Software Engineer",
    isActive: false,
    createdAt: new Date(now - day * 30),
  },
];

export const DEMO_EXPENSES = [
  {
    id: "exp-1",
    companyId: "demo-company",
    userId: "demo-user",
    title: "Client Lunch at The Ivy",
    description: "Lunch with Q4 prospect",
    amount: 87.50,
    currency: "GBP",
    category: "Meals & Entertainment",
    receiptUrl: null,
    status: "PAID",
    submittedAt: new Date(now - day * 14),
    reviewedById: "demo-manager",
    reviewedAt: new Date(now - day * 12),
    reviewNotes: null,
    paidAt: new Date(now - day * 10),
    user: { name: "John Smith", email: "john@demo.com", jobTitle: "Sales Executive", department: "Sales" },
    reviewedBy: { name: "Sarah Manager" },
  },
  {
    id: "exp-2",
    companyId: "demo-company",
    userId: "demo-user",
    title: "Train to Manchester",
    description: "Sales conference travel",
    amount: 124.00,
    currency: "GBP",
    category: "Travel",
    receiptUrl: null,
    status: "APPROVED",
    submittedAt: new Date(now - day * 7),
    reviewedById: "demo-manager",
    reviewedAt: new Date(now - day * 5),
    reviewNotes: null,
    paidAt: null,
    user: { name: "John Smith", email: "john@demo.com", jobTitle: "Sales Executive", department: "Sales" },
    reviewedBy: { name: "Sarah Manager" },
  },
  {
    id: "exp-3",
    companyId: "demo-company",
    userId: "demo-user",
    title: "Hotel — Manchester Conference",
    description: "Two nights accommodation",
    amount: 189.00,
    currency: "GBP",
    category: "Accommodation",
    receiptUrl: null,
    status: "PENDING",
    submittedAt: new Date(now - day * 2),
    reviewedById: null,
    reviewedAt: null,
    reviewNotes: null,
    paidAt: null,
    user: { name: "John Smith", email: "john@demo.com", jobTitle: "Sales Executive", department: "Sales" },
    reviewedBy: null,
  },
  {
    id: "exp-4",
    companyId: "demo-company",
    userId: "demo-user",
    title: "Parking at HQ",
    description: null,
    amount: 15.00,
    currency: "GBP",
    category: "Travel",
    receiptUrl: null,
    status: "DECLINED",
    submittedAt: new Date(now - day * 5),
    reviewedById: "demo-manager",
    reviewedAt: new Date(now - day * 4),
    reviewNotes: "Please use public transport per company policy",
    paidAt: null,
    user: { name: "John Smith", email: "john@demo.com", jobTitle: "Sales Executive", department: "Sales" },
    reviewedBy: { name: "Sarah Manager" },
  },
  {
    id: "exp-5",
    companyId: "demo-company",
    userId: "demo-user-2",
    title: "Adobe Creative Cloud",
    description: "Annual subscription renewal",
    amount: 599.88,
    currency: "GBP",
    category: "Software & Subscriptions",
    receiptUrl: null,
    status: "PENDING",
    submittedAt: new Date(now - day * 1),
    reviewedById: null,
    reviewedAt: null,
    reviewNotes: null,
    paidAt: null,
    user: { name: "Emma Wilson", email: "emma@demo.com", jobTitle: "Marketing Lead", department: "Marketing" },
    reviewedBy: null,
  },
  {
    id: "exp-6",
    companyId: "demo-company",
    userId: "demo-user-2",
    title: "Team Away Day Venue",
    description: "Q3 team offsite",
    amount: 1250.00,
    currency: "GBP",
    category: "Other",
    receiptUrl: null,
    status: "APPROVED",
    submittedAt: new Date(now - day * 10),
    reviewedById: "demo-manager",
    reviewedAt: new Date(now - day * 9),
    reviewNotes: null,
    paidAt: null,
    user: { name: "Emma Wilson", email: "emma@demo.com", jobTitle: "Marketing Lead", department: "Marketing" },
    reviewedBy: { name: "Sarah Manager" },
  },
];

export function isDemoSession(companyId: string) {
  return companyId === "demo-company";
}
